<?php

namespace Database\Seeders;

use App\Models\Everlas_Things;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Faker\Factory as Faker;


class RealEverlasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Kursi Besi',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Kursi Besi',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Kursi Bulat Besi',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Kursi Kayu Vintage',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Meja Besi',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Meja Bulat Besi Kecil',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Meja Bulat Besi Besar',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Rak Gantung Stainless',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Rak Standing',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Meja besi mini',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Kursi Gantung',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Structura',
            'nama_produk' => 'Pot Besi Las',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Paket Meja Besi',
            'nama_produk' => 'Kursi Besi',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Everlas_Things::create([
            'seri' => 'Furniture Stainless',
            'nama_produk' => 'Kursi Besi',
            'slug' => Str::random(10),
            'satuan' => 'Unit',
            'jenis_1' => 'Industrial',
            'jenis_2' => 'Tidak Ada',
            'garansi' => '3 bulan',
            'warna' => 'Hitam',
            'dimensi' => '1 m',
            'material_pendukung' => 'Tidak ada',
            'finishing' => 'Coating',
            'gambar_1' => 'photos/everlasgambar1.jpg',
            'gambar_2' => 'photos/everlasgambar2.jpg',
            'gambar_3' => 'photos/everlasgambar3.jpg',
            'armada_minimum' => 'Mobil Pick Up',
            'deskripsi_singkat' => 'Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things Deskripsi singkat Everlas Things',
            'stok' => 50,
            'item_terjual' => 10,
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);
    }

    private function randomDateTimeInCurrentMonth($faker)
    {
        $startOfMonth = Carbon::now()->startOfMonth();
        $endOfMonth = Carbon::now()->endOfMonth();

        return $faker->dateTimeBetween($startOfMonth, $endOfMonth);
    }
}
