<?php

namespace Database\Seeders;

use App\Models\Dedikasi_Flora;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class RealDedikasiFloraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        Dedikasi_Flora::create([
            'nama_latin' => 'Furcraea foetida',
            'nama_lokal' => 'Agave Strip Kuning',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Kuning',
            'penyiraman' => 'Ekstensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Ekstensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar2.jpg',
            'gambar_3' => 'photos/gambar1.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 80000,
            'harga_b2I_31_unit' => 80000,
            'harga_b2I_11_unit' => 85000,
            'harga_b2I_1_unit' => 88000,
            'harga_b2B_31_unit' => 88000,
            'harga_b2B_11_unit' => 93000,
            'harga_b2B_1_unit' => 98000,
            'harga_b2C_31_unit' => 98000,
            'harga_b2C_11_unit' => 1030000,
            'harga_b2C_1_unit' => 108000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Agave americana',
            'nama_lokal' => 'Agave King',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Kuning',
            'penyiraman' => 'Ekstensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Ekstensif',
            'gambar_1' => 'photos/gambar2.jpg',
            'gambar_2' => 'photos/gambar3.jpg',
            'gambar_3' => 'photos/gambar1.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 28000,
            'harga_b2I_31_unit' => 28000,
            'harga_b2I_11_unit' => 30000,
            'harga_b2I_1_unit' => 33000,
            'harga_b2B_31_unit' => 33000,
            'harga_b2B_11_unit' => 35000,
            'harga_b2B_1_unit' => 38000,
            'harga_b2C_31_unit' => 38000,
            'harga_b2C_11_unit' => 40000,
            'harga_b2C_1_unit' => 44000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Aglaonema dona carmen',
            'nama_lokal' => 'Aglo Dona Carmen',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Jingga',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar2.jpg',
            'gambar_2' => 'photos/gambar3.jpg',
            'gambar_3' => 'photos/gambar1.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 6000,
            'harga_b2I_31_unit' => 6000,
            'harga_b2I_11_unit' => 6000,
            'harga_b2I_1_unit' => 7000,
            'harga_b2B_31_unit' => 7000,
            'harga_b2B_11_unit' => 7000,
            'harga_b2B_1_unit' => 8000,
            'harga_b2C_31_unit' => 8000,
            'harga_b2C_11_unit' => 8000,
            'harga_b2C_1_unit' => 9000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Aglaonema',
            'nama_lokal' => 'Aglo Lipstik',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 6000,
            'harga_b2I_31_unit' => 6000,
            'harga_b2I_11_unit' => 6000,
            'harga_b2I_1_unit' => 7000,
            'harga_b2B_31_unit' => 7000,
            'harga_b2B_11_unit' => 7000,
            'harga_b2B_1_unit' => 8000,
            'harga_b2C_31_unit' => 8000,
            'harga_b2C_11_unit' => 8000,
            'harga_b2C_1_unit' => 9000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Imperata cylindrica',
            'nama_lokal' => 'Alang-Alang Putih',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 6000,
            'harga_b2I_31_unit' => 6000,
            'harga_b2I_11_unit' => 6000,
            'harga_b2I_1_unit' => 7000,
            'harga_b2B_31_unit' => 7000,
            'harga_b2B_11_unit' => 7000,
            'harga_b2B_1_unit' => 8000,
            'harga_b2C_31_unit' => 8000,
            'harga_b2C_11_unit' => 8000,
            'harga_b2C_1_unit' => 9000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Spathoglottis plicata',
            'nama_lokal' => 'Anggrek Tanah',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 6000,
            'harga_b2I_31_unit' => 6000,
            'harga_b2I_11_unit' => 6000,
            'harga_b2I_1_unit' => 7000,
            'harga_b2B_31_unit' => 7000,
            'harga_b2B_11_unit' => 7000,
            'harga_b2B_1_unit' => 8000,
            'harga_b2C_31_unit' => 8000,
            'harga_b2C_11_unit' => 8000,
            'harga_b2C_1_unit' => 9000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Dieffenbachia neon',
            'nama_lokal' => 'Blanceng Neon',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 6000,
            'harga_b2I_31_unit' => 6000,
            'harga_b2I_11_unit' => 6000,
            'harga_b2I_1_unit' => 7000,
            'harga_b2B_31_unit' => 7000,
            'harga_b2B_11_unit' => 7000,
            'harga_b2B_1_unit' => 8000,
            'harga_b2C_31_unit' => 8000,
            'harga_b2C_11_unit' => 8000,
            'harga_b2C_1_unit' => 9000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Euodia ridleyi',
            'nama_lokal' => 'Brokoli Kuning',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 6000,
            'harga_b2I_31_unit' => 6000,
            'harga_b2I_11_unit' => 6000,
            'harga_b2I_1_unit' => 7000,
            'harga_b2B_31_unit' => 7000,
            'harga_b2B_11_unit' => 7000,
            'harga_b2B_1_unit' => 8000,
            'harga_b2C_31_unit' => 8000,
            'harga_b2C_11_unit' => 8000,
            'harga_b2C_1_unit' => 9000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Bromelia sp.',
            'nama_lokal' => 'Bromel Giant',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 60000,
            'harga_b2I_31_unit' => 60000,
            'harga_b2I_11_unit' => 60000,
            'harga_b2I_1_unit' => 65000,
            'harga_b2B_31_unit' => 65000,
            'harga_b2B_11_unit' => 65000,
            'harga_b2B_1_unit' => 75000,
            'harga_b2C_31_unit' => 75000,
            'harga_b2C_11_unit' => 75000,
            'harga_b2C_1_unit' => 80000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Callathea',
            'nama_lokal' => 'Calathea',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 50 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 6000,
            'harga_b2I_31_unit' => 6000,
            'harga_b2I_11_unit' => 6000,
            'harga_b2I_1_unit' => 7000,
            'harga_b2B_31_unit' => 7000,
            'harga_b2B_11_unit' => 7000,
            'harga_b2B_1_unit' => 8000,
            'harga_b2C_31_unit' => 8000,
            'harga_b2C_11_unit' => 8000,
            'harga_b2C_1_unit' => 9000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Callathea lancifolia',
            'nama_lokal' => 'Calathea Bulu Ayam',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 6000,
            'harga_b2I_31_unit' => 6000,
            'harga_b2I_11_unit' => 6000,
            'harga_b2I_1_unit' => 7000,
            'harga_b2B_31_unit' => 7000,
            'harga_b2B_11_unit' => 7000,
            'harga_b2B_1_unit' => 8000,
            'harga_b2C_31_unit' => 8000,
            'harga_b2C_11_unit' => 8000,
            'harga_b2C_1_unit' => 9000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Dracaena surculosa',
            'nama_lokal' => 'Dracaena Golden',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 17000,
            'harga_b2I_31_unit' => 17000,
            'harga_b2I_11_unit' => 17000,
            'harga_b2I_1_unit' => 19000,
            'harga_b2B_31_unit' => 19000,
            'harga_b2B_11_unit' => 19000,
            'harga_b2B_1_unit' => 23000,
            'harga_b2C_31_unit' => 23000,
            'harga_b2C_11_unit' => 23000,
            'harga_b2C_1_unit' => 25000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Heliconia psittacorum',
            'nama_lokal' => 'Heliconia',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 7000,
            'harga_b2I_31_unit' => 7000,
            'harga_b2I_11_unit' => 7000,
            'harga_b2I_1_unit' => 9000,
            'harga_b2B_31_unit' => 9000,
            'harga_b2B_11_unit' => 9000,
            'harga_b2B_1_unit' => 12000,
            'harga_b2C_31_unit' => 12000,
            'harga_b2C_11_unit' => 12000,
            'harga_b2C_1_unit' => 15000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Monstera borsigiana',
            'nama_lokal' => 'Monstera borsigiana',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Kuning',
            'penyiraman' => 'Ekstensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Ekstensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar2.jpg',
            'gambar_3' => 'photos/gambar1.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 80000,
            'harga_b2I_31_unit' => 80000,
            'harga_b2I_11_unit' => 85000,
            'harga_b2I_1_unit' => 88000,
            'harga_b2B_31_unit' => 88000,
            'harga_b2B_11_unit' => 93000,
            'harga_b2B_1_unit' => 98000,
            'harga_b2C_31_unit' => 98000,
            'harga_b2C_11_unit' => 1030000,
            'harga_b2C_1_unit' => 108000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Nephrolepis sp.',
            'nama_lokal' => 'Pakis Kelabang',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 20-30 cm',
            'satuan' => 'Polybag',
            'diameter_tajuk' => 20,
            'strata' => 'Semak',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Merah',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Toleran Naungan',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 7000,
            'harga_b2I_31_unit' => 7000,
            'harga_b2I_11_unit' => 7000,
            'harga_b2I_1_unit' => 9000,
            'harga_b2B_31_unit' => 9000,
            'harga_b2B_11_unit' => 9000,
            'harga_b2B_1_unit' => 12000,
            'harga_b2C_31_unit' => 12000,
            'harga_b2C_11_unit' => 12000,
            'harga_b2C_1_unit' => 15000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Pennisetum purpureum',
            'nama_lokal' => 'Rumput Babat',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 'Tidak Ada',
            'satuan' => 'm2',
            'diameter_tajuk' => 20,
            'strata' => 'Rumput',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 22000,
            'harga_b2I_31_unit' => 22000,
            'harga_b2I_11_unit' => 22000,
            'harga_b2I_1_unit' => 25000,
            'harga_b2B_31_unit' => 25000,
            'harga_b2B_11_unit' => 25000,
            'harga_b2B_1_unit' => 28000,
            'harga_b2C_31_unit' => 28000,
            'harga_b2C_11_unit' => 28000,
            'harga_b2C_1_unit' => 32000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Axonopus compressus',
            'nama_lokal' => 'Rumput Gajah Mini',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 'Tidak Ada',
            'satuan' => 'm2',
            'diameter_tajuk' => 20,
            'strata' => 'Rumput',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 22000,
            'harga_b2I_31_unit' => 22000,
            'harga_b2I_11_unit' => 22000,
            'harga_b2I_1_unit' => 25000,
            'harga_b2B_31_unit' => 25000,
            'harga_b2B_11_unit' => 25000,
            'harga_b2B_1_unit' => 28000,
            'harga_b2C_31_unit' => 28000,
            'harga_b2C_11_unit' => 28000,
            'harga_b2C_1_unit' => 32000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Zoysia japonica',
            'nama_lokal' => 'Rumput Jepang',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 'Tidak Ada',
            'satuan' => 'm2',
            'diameter_tajuk' => 20,
            'strata' => 'Rumput',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 22000,
            'harga_b2I_31_unit' => 22000,
            'harga_b2I_11_unit' => 22000,
            'harga_b2I_1_unit' => 25000,
            'harga_b2B_31_unit' => 25000,
            'harga_b2B_11_unit' => 25000,
            'harga_b2B_1_unit' => 28000,
            'harga_b2C_31_unit' => 28000,
            'harga_b2C_11_unit' => 28000,
            'harga_b2C_1_unit' => 32000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Dichantium caricosum',
            'nama_lokal' => 'Rumput Lamuran',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 'Tidak Ada',
            'satuan' => 'm2',
            'diameter_tajuk' => 20,
            'strata' => 'Rumput',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 22000,
            'harga_b2I_31_unit' => 22000,
            'harga_b2I_11_unit' => 22000,
            'harga_b2I_1_unit' => 25000,
            'harga_b2B_31_unit' => 25000,
            'harga_b2B_11_unit' => 25000,
            'harga_b2B_1_unit' => 28000,
            'harga_b2C_31_unit' => 28000,
            'harga_b2C_11_unit' => 28000,
            'harga_b2C_1_unit' => 32000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Agrostis stolonifera',
            'nama_lokal' => 'Rumput Peking',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 'Tidak Ada',
            'satuan' => 'm2',
            'diameter_tajuk' => 20,
            'strata' => 'Rumput',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 22000,
            'harga_b2I_31_unit' => 22000,
            'harga_b2I_11_unit' => 22000,
            'harga_b2I_1_unit' => 25000,
            'harga_b2B_31_unit' => 25000,
            'harga_b2B_11_unit' => 25000,
            'harga_b2B_1_unit' => 28000,
            'harga_b2C_31_unit' => 28000,
            'harga_b2C_11_unit' => 28000,
            'harga_b2C_1_unit' => 32000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Delonix regia',
            'nama_lokal' => 'Flamboyan',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 400 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Sedang',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 49500,
            'harga_b2I_31_unit' => 49500,
            'harga_b2I_11_unit' => 49500,
            'harga_b2I_1_unit' => 540000,
            'harga_b2B_31_unit' => 540000,
            'harga_b2B_11_unit' => 540000,
            'harga_b2B_1_unit' => 585000,
            'harga_b2C_31_unit' => 585000,
            'harga_b2C_11_unit' => 585000,
            'harga_b2C_1_unit' => 630000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Terminalia mantaly',
            'nama_lokal' => 'Ketapang Kencana',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 250 cm - 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Sedang',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 49500,
            'harga_b2I_31_unit' => 49500,
            'harga_b2I_11_unit' => 49500,
            'harga_b2I_1_unit' => 540000,
            'harga_b2B_31_unit' => 540000,
            'harga_b2B_11_unit' => 540000,
            'harga_b2B_1_unit' => 585000,
            'harga_b2C_31_unit' => 585000,
            'harga_b2C_11_unit' => 585000,
            'harga_b2C_1_unit' => 630000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Wodyetya bifurcata',
            'nama_lokal' => 'Palem Ekor Tupai',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Sedang',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Roystenea regia',
            'nama_lokal' => 'Palem Putri',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Sedang',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Plumeria alba',
            'nama_lokal' => 'Kamboja Fosil Bali',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Sedang',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Wrightia religiosa',
            'nama_lokal' => 'Anting Putri',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Bambusa vulgaris',
            'nama_lokal' => 'Bambu Kuning',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Ficus Coreana',
            'nama_lokal' => 'Beringin Korea',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Melaleuca leucadendra',
            'nama_lokal' => 'Bonsai Kayu Putih',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Thuja orientalis',
            'nama_lokal' => 'Cemara Kipas',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Araucaria heterophylla',
            'nama_lokal' => 'Cemara Norflok',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Terminalia mantaly var.',
            'nama_lokal' => 'Ketapang Kencana Var.',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Olea europaea',
            'nama_lokal' => 'Olive',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Dedikasi_Flora::create([
            'nama_latin' => 'Phoenix canariensis',
            'nama_lokal' => 'Palem Kenari',
            'deskripsi_singkat' => 'Tanaman serbaguna dan tahan cuaca. Daun tebal berwarna hijau menyajikan sentuhan tropis. Cocok untuk lanskap kering, memberikan estetika unik dan perawatan minimal.',
            'slug' => Str::random(10),
            'spesifikasi' => 't = 300 cm',
            'satuan' => 'Batang',
            'diameter_tajuk' => 20,
            'strata' => 'Pohon Kecil',
            'warna_daun' => 'Hijau',
            'warna_bunga' => 'Tidak Ada',
            'penyiraman' => 'Intensif',
            'penyinaran' => 'Penuh',
            'pemupukan' => 'Extra Intensif',
            'gambar_1' => 'photos/gambar3.jpg',
            'gambar_2' => 'photos/gambar1.jpg',
            'gambar_3' => 'photos/gambar2.jpg',
            'stok' => 50,
            'item_terjual' => 10,
            'armada_minimum' => 'Motor',
            'harga_jual_projek_ideally' => 110000,
            'harga_b2I_31_unit' => 110000,
            'harga_b2I_11_unit' => 110000,
            'harga_b2I_1_unit' => 115000,
            'harga_b2B_31_unit' => 115000,
            'harga_b2B_11_unit' => 115000,
            'harga_b2B_1_unit' => 120000,
            'harga_b2C_31_unit' => 120000,
            'harga_b2C_11_unit' => 120000,
            'harga_b2C_1_unit' => 125000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);
    }

    private function randomDateTimeInCurrentMonth($faker)
    {
        $startOfMonth = Carbon::now()->startOfMonth();
        $endOfMonth = Carbon::now()->endOfMonth();

        return $faker->dateTimeBetween($startOfMonth, $endOfMonth);
    }
}
