<?php

namespace Database\Seeders;

use App\Models\Konkurito;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class RealKonkuritoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        Konkurito::create([
            'nama_produk' => 'Roster Persegi',
            'slug' => Str::random(10),
            'jenis' => 'Roster',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Roster Bata',
            'slug' => Str::random(10),
            'jenis' => 'Roster',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Abu Batu',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Grass Block',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Topi Uskup',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Segi Enam',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Kampak',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Trihex',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Tiga Dimensi',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Kotak Kecil',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Bata',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Kotak Diagram',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Paving Cacing',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Kansteen Jepit',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);

        Konkurito::create([
            'nama_produk' => 'Kansteen Jalan',
            'slug' => Str::random(10),
            'jenis' => 'Paving',
            'satuan' => 'Unit',
            'panjang' => 20,
            'lebar' => 15,
            'diameter' => 10,
            'tinggi' => 25,
            'tebal' => 5,
            'garansi' => '1 bulan',
            'warna_1' => 'Merah',
            'warna_2' => 'Biru',
            'gambar_1' => 'photos/konkuritogambar1.jpg',
            'gambar_2' => 'photos/konkuritogambar2.jpg',
            'gambar_3' => 'photos/konkuritogambar3.jpg',
            'gambar_4' => 'photos/konkuritogambar4.jpg',
            'gambar_5' => 'photos/konkuritogambar5.jpg',
            'armada_minimum' => 'Kargo Mobil',
            'stok' => 50,
            'item_terjual' => 10,
            'deskripsi_singkat' => 'Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito Deskripsi singkat Konkurito',
            'harga_jual_projek_ideally' => 120000,
            'harga_b2I_11_unit' => 100000,
            'harga_b2I_1_unit' => 90000,
            'harga_b2B_11_unit' => 90000,
            'harga_b2B_1_unit' => 80000,
            'harga_b2C_11_unit' => 80000,
            'harga_b2C_1_unit' => 70000,
            'tanggal_publikasi' => $this->randomDateTimeInCurrentMonth($faker),
            'created_at' => $this->randomDateTimeInCurrentMonth($faker),
            'created_by' => 1, // Ganti dengan ID user yang sesuai
        ]);
    }

    private function randomDateTimeInCurrentMonth($faker)
    {
        $startOfMonth = Carbon::now()->startOfMonth();
        $endOfMonth = Carbon::now()->endOfMonth();

        return $faker->dateTimeBetween($startOfMonth, $endOfMonth);
    }
}
